
USE its2026;

DROP TABLE IF EXISTS games;
CREATE TABLE GAMES (
    game_id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100),
    genere  VARCHAR(100),
    publisher VARCHAR(100),
    platform  VARCHAR(100),
    year INT CHECK (year > 1960)
);

INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Oregon Trail', 'Genere', 'MECC', 'HP 2100', 1971);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Pong', 'Genere', 'Atari, Inc.', 'Arcade', 1972);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Combat', 'Genere', 'Atari, Inc.', 'Atari 2600', 1977);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Zork', 'Genere', 'Infocom', 'PDP-10', 1977);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Space Invaders', 'Genere', 'Taito', 'Arcade', 1978);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Asteroids', 'Genere', 'Atari, Inc.', 'Arcade', 1979);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Adventure', 'Genere', 'Atari, Inc.', 'Atari 2600', 1980);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Battlezone', 'Genere', 'Atari, Inc.', 'Arcade', 1980);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Missile Command', 'Genere', 'Atari, Inc.', 'Arcade', 1980);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Pac-Man', 'Genere', 'Namco', 'Arcade', 1980);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Centipede', 'Genere', 'Atari, Inc.', 'Arcade', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Defender', 'Genere', 'Williams Entertainment', 'Arcade', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Donkey Kong', 'Genere', 'Nintendo', 'Arcade', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Frogger', 'Genere', 'Konami/Sega', 'Arcade', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Galaga', 'Genere', 'Namco', 'Arcade', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tempest', 'Genere', 'Atari, Inc.', 'Arcade', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wizardry: Proving Grounds of the Mad Overlord', 'Genere', 'Sir-Tech', 'Apple II', 1981);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Joust', 'Genere', 'Williams', 'Arcade', 1982);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ms. Pac-Man', 'Genere', 'Midway', 'Arcade', 1982);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Pitfall!', 'Genere', 'Activision', 'Atari 2600', 1982);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Robotron: 2084', 'Genere', 'Williams', 'Arcade', 1982);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Archon: The Light and the Dark', 'Genere', 'Electronic Arts', 'Atari 8-bit family', 1983);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Lode Runner', 'Genere', 'Broderbund', 'Apple II', 1983);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('M.U.L.E.', 'Genere', 'Electronic Arts', 'Atari 8-bit family', 1983);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Wars', 'Genere', 'Atari, Inc.', 'Arcade', 1983);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Elite', 'Genere', 'Acornsoft', 'BBC Micro', 1984);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Marble Madness', 'Genere', 'Atari Games', 'Arcade', 1984);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tetris', 'Genere', 'Elorg', 'Electronika 60', 1984);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gauntlet', 'Genere', 'Atari Games', 'Arcade', 1985);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ghosts \'n Goblins', 'Genere', 'Capcom', 'Arcade', 1985);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario Bros.', 'Genere', 'Nintendo', 'NES', 1985);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ultima IV: Quest of the Avatar', 'Genere', 'Origin Systems', 'Apple II', 1985);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Arkanoid', 'Genere', 'Taito', 'Arcade', 1986);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Bubble Bobble', 'Genere', 'Taito', 'Arcade', 1986);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda', 'Genere', 'Nintendo', 'NES', 1986);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Out Run', 'Genere', 'Sega', 'Arcade', 1986);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Contra', 'Genere', 'Konami', 'Arcade', 1987);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Double Dragon', 'Genere', 'Technos Japan', 'Arcade', 1987);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dungeon Master', 'Genere', 'FTL Games', 'Atari ST', 1987);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mike Tyson\'s Punch-Out!!', 'Genere', 'Nintendo', 'NES', 1987);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('R-Type', 'Genere', 'Irem', 'Arcade', 1987);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sid Meier\'s Pirates!', 'Genere', 'MicroProse', 'Commodore 64', 1987);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mega Man 2', 'Genere', 'Capcom', 'NES', 1988);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ninja Gaiden', 'Genere', 'Tecmo', 'NES', 1988);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario Bros. 3', 'Genere', 'Nintendo', 'NES', 1988);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Final Fight', 'Genere', 'Capcom', 'Arcade', 1989);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Populous', 'Genere', 'Electronic Arts', 'Amiga', 1989);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Prince of Persia', 'Genere', 'Broderbund', 'Apple II', 1989);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('SimCity', 'Genere', 'Maxis', 'Amiga, Macintosh', 1989);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Secret of Monkey Island', 'Genere', 'LucasArts', 'PC', 1990);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Speedball 2: Brutal Deluxe', 'Genere', 'Image Works', 'Atari ST', 1990);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario World', 'Genere', 'Nintendo', 'Super NES', 1990);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wing Commander', 'Genere', 'Origin Systems', 'PC', 1990);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Another World', 'Genere', 'Delphine Software', 'Amiga, Atari ST', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Civilization', 'Genere', 'MicroProse', 'PC', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Final Fantasy IV', 'Genere', 'Square', 'Super NES', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: A Link to the Past', 'Genere', 'Nintendo', 'Super NES', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Lemmings', 'Genere', 'Psygnosis', 'Amiga', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Micro Machines', 'Genere', 'Camerica', 'NES', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Monkey Island 2: LeChuck\'s Revenge', 'Genere', 'LucasArts', 'PC', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sonic the Hedgehog', 'Genere', 'Sega', 'Sega Genesis', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Street Fighter II', 'Genere', 'Capcom', 'Arcade', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Castlevania IV', 'Genere', 'Konami', 'Super NES', 1991);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Alone in the Dark', 'Genere', 'Infogrames', 'PC', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Contra III: The Alien Wars', 'Genere', 'Konami', 'Super NES', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dune II', 'Genere', 'Virgin Games', 'PC', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Flashback', 'Genere', 'U.S. Gold', 'Amiga', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Indiana Jones and the Fate of Atlantis', 'Genere', 'LucasArts', 'PC', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mortal Kombat', 'Genere', 'Midway', 'Arcade', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sensible Soccer', 'Genere', 'Renegade Software', 'Amiga, Atari ST', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sonic the Hedgehog 2', 'Genere', 'Sega', 'Sega Genesis', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Control II', 'Genere', 'Accolade', 'PC', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Streets of Rage 2', 'Genere', 'Sega', 'Sega Genesis', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario Kart', 'Genere', 'Nintendo', 'Super NES', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ultima VII: The Black Gate', 'Genere', 'Origin Systems', 'PC', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Virtua Racing', 'Genere', 'Sega', 'Arcade', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wolfenstein 3D', 'Genere', 'Apogee Software', 'PC', 1992);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Day of the Tentacle', 'Genere', 'LucasArts', 'PC', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Daytona USA', 'Genere', 'Sega', 'Arcade', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Doom', 'Genere', 'id Software', 'PC', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gunstar Heroes', 'Genere', 'Sega', 'Sega Genesis', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: Link\'s Awakening', 'Genere', 'Nintendo', 'Game Boy', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mega Man X', 'Genere', 'Capcom', 'Super NES', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mortal Kombat II', 'Genere', 'Midway', 'Arcade', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Myst', 'Genere', 'Broderbund', 'Macintosh', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('NBA Jam', 'Genere', 'Midway', 'Arcade', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Phantasy Star IV', 'Genere', 'Sega', 'Sega Genesis', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ridge Racer', 'Genere', 'Namco', 'Arcade', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sam & Max Hit the Road', 'Genere', 'LucasArts', 'PC', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Secret of Mana', 'Genere', 'Square', 'Super NES', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Samurai Shodown', 'Genere', 'SNK', 'Arcade', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('SimCity 2000', 'Genere', 'Maxis', 'Macintosh', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Fox', 'Genere', 'Nintendo', 'Super NES', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Syndicate', 'Genere', 'Electronic Arts', 'Amiga, PC', 1993);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Donkey Kong Country', 'Genere', 'Nintendo', 'Super NES', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Doom II', 'Genere', 'GT Interactive', 'PC', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('EarthBound', 'Genere', 'Nintendo', 'Super NES', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Final Fantasy VI', 'Genere', 'Square', 'Super NES', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sega Rally Championship', 'Genere', 'Sega', 'Arcade', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Sensible World of Soccer', 'Genere', 'Renegade Software', 'Amiga', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Wars: TIE Fighter', 'Genere', 'LucasArts', 'PC', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Metroid', 'Genere', 'Nintendo', 'Super NES', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tempest 2000', 'Genere', 'Atari Corporation', 'Atari Jaguar', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Theme Park', 'Genere', 'Electronic Arts', 'Amiga, PC', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Virtua Fighter 2', 'Genere', 'Sega', 'Arcade', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('X-COM: UFO Defense', 'Genere', 'MicroProse', 'PC', 1994);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Chrono Trigger', 'Genere', 'Square', 'Super NES', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Command & Conquer', 'Genere', 'Virgin Interactive', 'PC', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('MechWarrior 2: 31st Century Combat', 'Genere', 'Activision', 'PC', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Warcraft II: Tides of Darkness', 'Genere', 'Blizzard Entertainment', 'PC', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wipeout', 'Genere', 'Psygnosis', 'PC, PlayStation', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Worms', 'Genere', 'Ocean Software', 'Amiga', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Yoshi\'s Island', 'Genere', 'Nintendo', 'Super NES', 1995);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Civilization II', 'Genere', 'MicroProse', 'PC', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Command & Conquer: Red Alert', 'Genere', 'Virgin Interactive', 'PC', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Duke Nukem 3D', 'Genere', 'GT Interactive', 'PC', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mario Kart 64', 'Genere', 'Nintendo', 'Nintendo 64', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Nights into Dreams...', 'Genere', 'Sega', 'Saturn', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('PaRappa the Rapper', 'Genere', 'Sony Computer Entertainment', 'PlayStation', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Pokémon Redand Blue', 'Genere', 'Nintendo', 'Game Boy', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Quake', 'Genere', 'GT Interactive', 'PC', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Resident Evil', 'Genere', 'Capcom', 'PlayStation', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario 64', 'Genere', 'Nintendo', 'Nintendo 64', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tekken 3', 'Genere', 'Namco', 'Arcade', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tomb Raider', 'Genere', 'Eidos Interactive', 'Saturn, PC, PlayStation', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wave Race 64', 'Genere', 'Nintendo', 'Nintendo 64', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wipeout 2097', 'Genere', 'Psygnosis', 'PlayStation', 1996);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Age of Empires', 'Genere', 'Microsoft', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Castlevania: Symphony of the Night', 'Genere', 'Konami', 'PlayStation', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Diablo', 'Genere', 'Blizzard Entertainment', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Fallout', 'Genere', 'Interplay Entertainment', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Final Fantasy Tactics', 'Genere', 'Square', 'PlayStation', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Final Fantasy VII', 'Genere', 'Square', 'PlayStation', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('GoldenEye 007', 'Genere', 'Nintendo', 'Nintendo 64', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gran Turismo', 'Genere', 'Sony Computer Entertainment', 'PlayStation', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grand Theft Auto', 'Genere', 'BMG Interactive', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Quake II', 'Genere', 'Activision', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Fox 64', 'Genere', 'Nintendo', 'Nintendo 64', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Wars Jedi Knight: Dark Forces II', 'Genere', 'LucasArts', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Total Annihilation', 'Genere', 'Cavedog Entertainment', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ultima Online', 'Genere', 'Electronic Arts', 'PC', 1997);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Baldur\'s Gate', 'Genere', 'Black Isle Studios', 'PC', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Crash Bandicoot: Warped', 'Genere', 'Sony Computer Entertainment', 'PlayStation', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dance Dance Revolution', 'Genere', 'Konami', 'Arcade', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Fallout 2', 'Genere', 'Interplay Entertainment', 'PC', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grim Fandango', 'Genere', 'LucasArts', 'PC', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Half-Life', 'Genere', 'Sierra Studios', 'PC', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: Ocarina of Time', 'Genere', 'Nintendo', 'Nintendo 64', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Metal Gear Solid', 'Genere', 'Konami', 'PlayStation', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Panzer Dragoon Saga', 'Genere', 'Sega', 'Saturn', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Resident Evil 2', 'Genere', 'Capcom', 'PlayStation', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Soulcalibur', 'Genere', 'Namco', 'Arcade', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('StarCraft', 'Genere', 'Blizzard Entertainment', 'PC', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Suikoden II', 'Genere', 'Konami', 'PlayStation', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Thief: The Dark Project', 'Genere', 'Eidos Interactive', 'PC', 1998);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Age of Empires II', 'Genere', 'Microsoft', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('EverQuest', 'Genere', 'Sony Online Entertainment', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Homeworld', 'Genere', 'Sierra Studios', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Planescape: Torment', 'Genere', 'Interplay Entertainment', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Pokémon Goldand Silver', 'Genere', 'Nintendo', 'Game Boy Color', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Quake III: Arena', 'Genere', 'Activision', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Shenmue', 'Genere', 'Sega', 'Dreamcast', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Silent Hill', 'Genere', 'Konami', 'PlayStation', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('System Shock 2', 'Genere', 'Electronic Arts', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Unreal Tournament', 'Genere', 'GT Interactive', 'PC', 1999);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Baldur\'s Gate II: Shadows of Amn', 'Genere', 'Black Isle Studios', 'PC', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Counter-Strike', 'Genere', 'Valve', 'PC', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Deus Ex', 'Genere', 'Eidos Interactive', 'PC', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Diablo II', 'Genere', 'Blizzard Entertainment', 'PC', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Jet Set Radio', 'Genere', 'Sega', 'Dreamcast', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: Majora\'s Mask', 'Genere', 'Nintendo', 'Nintendo 64', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Marvel vs. Capcom 2: New Age of Heroes', 'Genere', 'Capcom', 'Arcade', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Sims', 'Genere', 'Electronic Arts', 'PC', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Thief II: The Metal Age', 'Genere', 'Eidos Interactive', 'PC', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tony Hawk\'s Pro Skater 2', 'Genere', 'Activision', 'PlayStation', 2000);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Advance Wars', 'Genere', 'Nintendo', 'Game Boy Advance', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Animal Crossing', 'Genere', 'Nintendo', 'GameCube', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Devil May Cry', 'Genere', 'Capcom', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Final Fantasy X', 'Genere', 'Square', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gran Turismo 3: A-Spec', 'Genere', 'Sony Computer Entertainment', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grand Theft Auto III', 'Genere', 'Rockstar Games', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Halo: Combat Evolved', 'Genere', 'Microsoft Game Studios', 'Xbox', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ico', 'Genere', 'Sony Computer Entertainment', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ikaruga', 'Genere', 'Treasure', 'Arcade', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Max Payne', 'Genere', 'Gathering of Developers', 'PC', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Metal Gear Solid 2: Sons of Liberty', 'Genere', 'Konami', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Phoenix Wright: Ace Attorney', 'Genere', 'Capcom', 'Game Boy Advance', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Rez', 'Genere', 'Sega', 'Dreamcast, PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Silent Hill 2', 'Genere', 'Konami', 'PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Smash Bros. Melee', 'Genere', 'Nintendo', 'GameCube', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tony Hawk\'s Pro Skater 3', 'Genere', 'Activision', 'PlayStation, PlayStation 2', 2001);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Battlefield 1942', 'Genere', 'Electronic Arts', 'PC', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Elder Scrolls III: Morrowind', 'Genere', 'Bethesda Softworks', 'PC', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Eternal Darkness: Sanity\'s Requiem', 'Genere', 'Nintendo', 'GameCube', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grand Theft Auto: Vice City', 'Genere', 'Rockstar Games', 'PlayStation 2', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Kingdom Hearts', 'Genere', 'Square', 'PlayStation 2', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: The Wind Waker', 'Genere', 'Nintendo', 'GameCube', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Metroid Prime', 'Genere', 'Nintendo', 'GameCube', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Soulcalibur II', 'Genere', 'Namco', 'Arcade', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tom Clancy\'s Splinter Cell', 'Genere', 'Ubisoft', 'Xbox', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Warcraft III: Reign of Chaos', 'Genere', 'Blizzard Entertainment', 'PC, Macintosh', 2002);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Beyond Good & Evil', 'Genere', 'Ubisoft', 'PlayStation 2', 2003);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('F-Zero GX', 'Genere', 'Nintendo', 'GameCube', 2003);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Max Payne 2: The Fall of Max Payne', 'Genere', 'Rockstar Games', 'PC', 2003);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Prince of Persia: The Sands of Time', 'Genere', 'Ubisoft', 'PlayStation 2', 2003);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Star Wars: Knights of the Old Republic', 'Genere', 'LucasArts', 'Xbox', 2003);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('WarioWare, Inc.: Mega Microgames!', 'Genere', 'Nintendo', 'Game Boy Advance', 2003);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Burnout 3: Takedown', 'Genere', 'Electronic Arts', 'PlayStation 2, Xbox', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Chronicles of Riddick: Escape from Butcher Bay', 'Genere', 'Vivendi Universal Games', 'Xbox', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dragon Quest VIII', 'Genere', 'Square Enix', 'PlayStation 2', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gran Turismo 4', 'Genere', 'Sony Computer Entertainment', 'PlayStation 2', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grand Theft Auto: San Andreas', 'Genere', 'Rockstar Games', 'PlayStation 2', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Half-Life 2', 'Genere', 'Valve', 'PC', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Halo 2', 'Genere', 'Microsoft Game Studios', 'Xbox', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Katamari Damacy', 'Genere', 'Namco', 'PlayStation 2', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Metal Gear Solid 3: Snake Eater', 'Genere', 'Konami', 'PlayStation 2', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Rome: Total War', 'Genere', 'Activision', 'PC', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Sims 2', 'Genere', 'Electronic Arts', 'PC', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('World of Warcraft', 'Genere', 'Blizzard Entertainment', 'PC, Macintosh', 2004);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Call of Duty 2', 'Genere', 'Activision', 'PC', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Civilization IV', 'Genere', '2K Games', 'PC', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Devil May Cry 3: Dante\'s Awakening', 'Genere', 'Capcom', 'PlayStation 2', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('God of War', 'Genere', 'Sony Computer Entertainment', 'PlayStation 2', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Guitar Hero', 'Genere', 'RedOctane', 'PlayStation 2', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Psychonauts', 'Genere', 'Majesco', 'PC, Xbox', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Resident Evil 4', 'Genere', 'Capcom', 'GameCube', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Shadow of the Colossus', 'Genere', 'Sony Computer Entertainment', 'PlayStation 2', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Tom Clancy\'s Splinter Cell: Chaos Theory', 'Genere', 'Ubisoft', 'GameCube, PC, PlayStation 2, Xbox', 2005);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Company of Heroes', 'Genere', 'THQ', 'PC', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Elder Scrolls IV: Oblivion', 'Genere', '2K Games, Bethesda Softworks', 'PC, Xbox 360', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gears of War', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Hitman: Blood Money', 'Genere', 'Eidos Interactive', 'PC, PlayStation 2, Xbox, Xbox 360', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: Twilight Princess', 'Genere', 'Nintendo', 'GameCube, Wii', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Ōkami', 'Genere', 'Capcom', 'PlayStation 2', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Wii Sports', 'Genere', 'Nintendo', 'Wii', 2006);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('BioShock', 'Genere', '2K Games', 'PC, Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Call of Duty 4: Modern Warfare', 'Genere', 'Activision', 'PC, PlayStation 3, Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('God of War II', 'Genere', 'Sony Computer Entertainment', 'PlayStation 2', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Halo 3', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mass Effect', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Portal', 'Genere', 'Valve', 'PC, Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Rock Band', 'Genere', 'MTV Games', 'PlayStation 3, Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario Galaxy', 'Genere', 'Nintendo', 'Wii', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Team Fortress 2', 'Genere', 'Valve', 'PC, Xbox 360', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The World Ends with You', 'Genere', 'Square Enix', 'Nintendo DS', 2007);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Braid', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Burnout Paradise', 'Genere', 'Electronic Arts', 'PC, PlayStation 3, Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dead Space', 'Genere', 'Electronic Arts', 'PlayStation 3, Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Fable II', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Fallout 3', 'Genere', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Gears of War 2', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grand Theft Auto IV', 'Genere', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Left 4 Dead', 'Genere', 'Valve', 'PC, Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('LittleBigPlanet', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Persona 4', 'Genere', 'Atlus', 'PlayStation 2', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Rock Band 2', 'Genere', 'MTV Games', 'Xbox 360', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Spelunky', 'Genere', 'Derek Yu', 'PC', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Street Fighter IV', 'Genere', 'Capcom', 'Arcade', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Valkyria Chronicles', 'Genere', 'Sega', 'PlayStation 3', 2008);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Angry Birds', 'Genere', 'Rovio Entertainment', 'Maemo, iOS', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Assassin\'s Creed II', 'Genere', 'Ubisoft', 'PlayStation 3, Xbox 360', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Batman: Arkham Asylum', 'Genere', 'Eidos Interactive, Warner Bros. Interactive Entertainment', 'PlayStation 3, Xbox 360', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Bayonetta', 'Genere', 'Sega', 'PlayStation 3, Xbox 360', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Borderlands', 'Genere', '2K Games', 'PC, PlayStation 3, Xbox 360', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Demon\'s Souls', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dragon Age: Origins', 'Genere', 'Electronic Arts', 'PC, PlayStation 3, Xbox 360', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('League of Legends', 'Genere', 'Riot Games', 'PC', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Left 4 Dead 2', 'Genere', 'Valve', 'PC, Xbox 360', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Plants vs. Zombies', 'Genere', 'PopCap Games', 'PC, Macintosh', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Uncharted 2: Among Thieves', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2009);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('God of War III', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Heavy Rain', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Limbo', 'Genere', 'Microsoft Game Studios', 'Xbox 360', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Mass Effect 2', 'Genere', 'Electronic Arts', 'PC, Xbox 360', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Red Dead Redemption', 'Genere', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Rock Band 3', 'Genere', 'MTV Games', 'Nintendo DS, PlayStation 3, Xbox 360, Wii', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('StarCraft II: Wings of Liberty', 'Genere', 'Blizzard Entertainment', 'PC, Macintosh', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario Galaxy 2', 'Genere', 'Nintendo', 'Wii', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Meat Boy', 'Genere', 'Team Meat', 'Xbox 360', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Xenoblade Chronicles', 'Genere', 'Nintendo', 'Wii', 2010);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Batman: Arkham City', 'Genere', 'Warner Bros. Interactive Entertainment', 'PlayStation 3, Xbox 360', 2011);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dark Souls', 'Genere', 'Namco Bandai Games', 'PlayStation 3, Xbox 360', 2011);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Elder Scrolls V: Skyrim', 'Genere', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2011);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Minecraft', 'Genere', 'Mojang', 'PC', 2011);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Portal 2', 'Genere', 'Valve', 'PC, PlayStation 3, Xbox 360', 2011);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dishonored', 'Genere', 'Bethesda Softworks', 'PC, PlayStation 3, Xbox 360', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Far Cry 3', 'Genere', 'Ubisoft', 'PC, PlayStation 3, Xbox 360', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Fire Emblem: Awakening', 'Genere', 'Nintendo', 'Nintendo 3DS', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Journey', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Hotline Miami', 'Genere', 'Devolver Digital', 'PC', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Walking Dead', 'Genere', 'Telltale Games', 'PC, PlayStation 3, Xbox 360', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('XCOM: Enemy Unknown', 'Genere', '2K Games', 'PC, PlayStation 3, Xbox 360', 2012);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('BioShock Infinite', 'Genere', '2K Games', 'PC, PlayStation 3, Xbox 360', 2013);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Dota 2', 'Genere', 'Valve', 'PC', 2013);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Grand Theft Auto V', 'Genere', 'Rockstar Games', 'PlayStation 3, Xbox 360', 2013);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Last of Us', 'Genere', 'Sony Computer Entertainment', 'PlayStation 3', 2013);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Papers, Please', 'Genere', '3909 LLC', 'PC, Macintosh', 2013);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Destiny', 'Genere', 'Bungie', 'PlayStation 3, PlayStation 4, Xbox 360, Xbox One', 2014);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Shovel Knight', 'Genere', 'Yacht Club Games', 'Nintendo 3DS, PC, Wii U', 2014);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Bloodborne', 'Genere', 'Sony Computer Entertainment', 'PlayStation 4', 2015);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Rocket League', 'Genere', 'Psyonix', 'PC, PlayStation 4', 2015);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Undertale', 'Genere', 'Toby Fox', 'PC, Macintosh', 2015);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Witcher 3: Wild Hunt', 'Genere', 'CD Projekt', 'PC, PlayStation 4, Xbox One', 2015);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Inside', 'Genere', 'Playdead', 'Xbox One', 2016);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Overwatch', 'Genere', 'Blizzard Entertainment', 'PC, PlayStation 4, Xbox One', 2016);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Stardew Valley', 'Genere', 'ConcernedApe', 'PC', 2016);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Uncharted 4: A Thief\'s End', 'Genere', 'Sony Computer Entertainment', 'PlayStation 4', 2016);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('The Legend of Zelda: Breath of the Wild', 'Genere', 'Nintendo', 'Nintendo Switch, Wii U', 2017);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Super Mario Odyssey', 'Genere', 'Nintendo', 'Nintendo Switch', 2017);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('God of War', 'Genere', 'Sony Interactive Entertainment', 'PlayStation 4', 2018);
INSERT INTO games (nome, genere, publisher, platform, year) VALUES ('Red Dead Redemption 2', 'Genere', 'Rockstar Games', 'PlayStation 4, Xbox One', 2018);
