concetti = [
    "Algoritmo",
    "Programma",
    "Linguaggio di programmazione",
    {"nome": "Paradigma di programmazione",
        "stile": "Procedurale",
        "stile": "Orientato agli oggetti",
        "stile": "Funzionale",
        "stile": "Logica"},
    "Dotazione:",
        "Variabile",
        "Operatori di espressioni",
        "Funzione, Procedura, metodo",
        "Tipi di dato",
        "Strutture dati",
            "liste- set - tuple - dic",
        "Struttura di controllo: condizioni(selezione) e cili(iterazione)",
        "Classi e  Oggetti",
            'ereditarieta',
            'polimorfismo',
            'incapsulamento',
            'astrazione',
        "Gestione degli errori di esecuzione",
        "Test e debug",
        "librerie e framework",

]