insert into libri set titolo = 'L\'ombra del vento', pagine = '567', prezzo = 15.99, editore_id = 1;
insert into libri set titolo = 'Il nome della rosa', pagine = '512', prezzo = 12.5, editore_id = 1;
insert into libri set titolo = '1984', pagine = '328', prezzo = 10.9, editore_id = 1;
insert into libri set titolo = 'Il piccolo principe', pagine = '96', prezzo = 8.99, editore_id = 1;
insert into libri set titolo = 'Orgoglio e pregiudizio', pagine = '352', prezzo = 11.99, editore_id = 1;
insert into libri set titolo = 'Harry Potter e la pietra filosofale', pagine = '309', prezzo = 14.5, editore_id = 1;
insert into libri set titolo = 'Il grande Gatsby', pagine = '180', prezzo = 9.99, editore_id = 1;
insert into libri set titolo = 'Il ritratto di Dorian Gray', pagine = '256', prezzo = 6.9, editore_id = 1;
insert into libri set titolo = 'Il signore degli anelli', pagine = '1248', prezzo = 35.0, editore_id = 1;
insert into libri set titolo = 'La casa degli spiriti', pagine = '448', prezzo = 13.99, editore_id = 1;
insert into libri set titolo = 'Cent\'anni di solitudine', pagine = '432', prezzo = 14.0, editore_id = 1;
insert into libri set titolo = 'La solitudine dei numeri primi', pagine = '304', prezzo = 10.5, editore_id = 1;
insert into libri set titolo = 'Anna Karenina', pagine = '864', prezzo = 16.99, editore_id = 1;
insert into libri set titolo = 'Il cacciatore di aquiloni', pagine = '391', prezzo = 13.49, editore_id = 1;
insert into libri set titolo = 'Don Chisciotte della Mancia', pagine = '928', prezzo = 19.9, editore_id = 1;
insert into libri set titolo = 'La fattoria degli animali', pagine = '141', prezzo = 8.49, editore_id = 1;
insert into libri set titolo = 'Dracula', pagine = '488', prezzo = 7.9, editore_id = 1;
insert into libri set titolo = 'Viaggio al centro della Terra', pagine = '284', prezzo = 9.99, editore_id = 1;
insert into libri set titolo = 'Moby Dick', pagine = '720', prezzo = 15.5, editore_id = 1;
insert into libri set titolo = 'I promessi sposi', pagine = '712', prezzo = 12.99, editore_id = 1;
